# Generated by Django 5.2.4 on 2025-08-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order_num', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='calculations.parametergroup')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('coefficient', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='calculations.parameter')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationParameterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_before', models.CharField(max_length=300)),
                ('value_after', models.CharField(max_length=300)),
                ('actions_description', models.TextField(blank=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_data', to='calculations.calculation')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculations.parameter')),
            ],
            options={
                'unique_together': {('calculation', 'parameter')},
            },
        ),
    ]
