# Generated by Django 5.2.4 on 2025-08-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_parametergroup_parameter_parameteroption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_sum', models.FloatField(default=0.0)),
                ('before_percentage', models.FloatField(default=0.0)),
                ('before_linguistic_level', models.CharField(default='Не оценивается', max_length=50)),
                ('after_sum', models.FloatField(default=0.0)),
                ('after_percentage', models.FloatField(default=0.0)),
                ('after_linguistic_level', models.CharField(default='Не оценивается', max_length=50)),
                ('max_sum', models.FloatField(default=0.0)),
                ('difference', models.FloatField(default=0.0)),
                ('conclusion', models.CharField(default='', max_length=100)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculations.calculation')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculations.parametergroup')),
            ],
            options={
                'verbose_name': 'Результат расчета',
                'verbose_name_plural': 'Результаты расчетов',
                'unique_together': {('calculation', 'group')},
            },
        ),
    ]
