# Generated by Django 5.2.4 on 2025-09-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0003_calculationresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationparameterdata',
            name='value_after',
        ),
        migrations.AddField(
            model_name='calculation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='calculations.calculation'),
        ),
    ]
