# Generated by Django 5.2.4 on 2025-09-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0004_remove_calculationparameterdata_value_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationresult',
            name='after_linguistic_level',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='after_percentage',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='after_sum',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='difference',
        ),
    ]
