# Generated by Django 5.2.4 on 2025-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0005_remove_calculationresult_after_linguistic_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='conclusion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='difference',
            field=models.FloatField(default=0.0),
        ),
    ]
