# Generated by Django 5.2.4 on 2025-10-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0006_calculationresult_conclusion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.CharField(max_length=12, verbose_name='ИНН')),
                ('KPP', models.CharField(max_length=9, verbose_name='КПП')),
                ('OGRN', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование организации')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AlterModelOptions(
            name='calculation',
            options={'verbose_name': 'Расчёт', 'verbose_name_plural': 'Расчёты'},
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='organisation_INN',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='organisation_KPP',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='organisation_OGRN',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='organisation_address',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='organisation_name',
        ),
        migrations.AddField(
            model_name='calculation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='calculations.organisation', verbose_name='Организация'),
        ),
    ]
