# Generated by Django 5.2.4 on 2025-12-23 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0007_organisation_alter_calculation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Отрасль промышленности')),
            ],
        ),
        migrations.CreateModel(
            name='RiskCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год расчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_short_shift', models.BooleanField(default=False, verbose_name='Смены менее 2 часов')),
                ('result', models.FloatField(verbose_name='Результат расчёта')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculations.industry', verbose_name='Отрасль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расчёт индивидуального риска',
                'verbose_name_plural': 'Расчёты индивидуального риска',
            },
        ),
        migrations.CreateModel(
            name='DeathStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('deaths', models.PositiveIntegerField(verbose_name='Количество погибших')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_stats', to='calculations.industry', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Смерти за год',
                'verbose_name_plural': 'Смерти за годы',
                'unique_together': {('industry', 'year')},
            },
        ),
    ]
