# Generated by Django 5.2.4 on 2025-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0008_industry_riskcalculation_deathstatistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deathstatistic',
            options={'verbose_name': 'Смерти за год'},
        ),
        migrations.AlterModelOptions(
            name='riskcalculation',
            options={'verbose_name': 'Расчёт индивидуального риска'},
        ),
        migrations.AddField(
            model_name='deathstatistic',
            name='workers_in_industry',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество работников в отрасли'),
            preserve_default=False,
        ),
    ]
