# Generated by Django 5.2.4 on 2025-12-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0009_alter_deathstatistic_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskcalculation',
            old_name='created_at',
            new_name='created',
        ),
    ]
